### ISSUE TITLE
I2C.transaction actually returns false when succeeds

### ISSUE THREAD

**Issue by LTSENG01** [1757WestwoodRobotics/2018-PowerUp#2]
https://github.com/1757WestwoodRobotics/2018-PowerUp/blob/b7fcc103280bf47b748db359af81377701b05af4/src/main/java/org/whsrobotics/communications/ArduinoI2C.java#L26

It's a weird thing about WPILib, but the boolean `I2C.transaction()` returns actually indicates if it failed (true) or succeeded (false).

**Comment by cgopal** [comment]
ok thanks... should looked at I2C returns.. will update comment to reflect the same... logic does not change.
