### ISSUE TITLE
Fix Arduino/Ultrasonic

### ISSUE THREAD

**Issue by LTSENG01** [1757WestwoodRobotics/2018-PowerUp#24]
When running the automated sequence for grabbing cubes, it is getting stuck in the loop in the Arduino.getDistance() method. It is locking up the drive train for some reason - I don't know why, but it's an urgent issue that needs to be fixed. Some Timer.delay() may be blocking the DriveTrain's thread, but that is unlikely the case.

We can retry semaphores and mutex locks (if unlocked, create a new Thread?), but I don't want to spend too much time debugging it.

**Comment by cgopal** [comment]
I found a buffer overrun issue with the led commands on the Arduino side. Hopefully this fixes the Arduino free freeze. Now will need to look at Robot code to see how to eliminate the loop.

**Comment by LTSENG01** [comment]
I don't know why the DriveTrain is locking up still. We can try debugging and inspecting each thread?
